
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: boyaku_development

test:
  <<: *default
  database: boyaku_test

production:
  <<: *default
  database: boyaku_production
  username: boyaku
  password: <%= ENV['BOYAKU_DATABASE_PASSWORD'] %>
